export const CATEGORIES = [
  { id: "retail", label: "Retail Shop", icon: "🏪" },
  { id: "restaurant", label: "Restaurant", icon: "🍽️" },
  { id: "grocery", label: "Grocery Store", icon: "🛒" },
  { id: "fashion", label: "Fashion", icon: "👗" },
  { id: "electronics", label: "Electronics", icon: "📱" },
  { id: "manufacturing", label: "Manufacturing", icon: "🏭" },
  { id: "services", label: "Services", icon: "🛠️" },
  { id: "pharmacy", label: "Pharmacy", icon: "💊" },
  { id: "supermarket", label: "Supermarket", icon: "🏬" },
  { id: "cafe", label: "Cafe", icon: "☕" },
  { id: "wholesale", label: "Wholesale", icon: "📦" },
  { id: "distributor", label: "Distributor", icon: "🚚" },
  { id: "healthcare", label: "Healthcare", icon: "🏥" },
  { id: "education", label: "Education", icon: "🎓" },
  { id: "other", label: "Other", icon: "📦" },
];

// NOTE: Full CATEGORY_FEATURES and remaining constants will be in follow-up if this is truncated - use complete file from local
export const CATEGORY_FEATURES: Record<string, string[]> = {
  retail: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Credit Tracking", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant"],
  restaurant: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Menu Management", "Ingredient Tracking", "Expiry Alerts", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant"],
  grocery: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Expiry Alerts", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant"],
  fashion: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant", "E-commerce Storefront"],
  electronics: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant", "E-commerce Storefront"],
  manufacturing: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Production Tracking", "Expense Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant", "Multi-branch Support"],
  services: ["Sales Recording", "Staff Management", "Cash Flow Analysis", "Expense Management", "Customer Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant"],
  pharmacy: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Expiry Alerts", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant"],
  supermarket: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Expiry Alerts", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant", "Multi-branch Support"],
  cafe: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Menu Management", "Ingredient Tracking", "Expiry Alerts", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant"],
  wholesale: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Credit Tracking", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant", "Multi-branch Support"],
  distributor: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Credit Tracking", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant", "Multi-branch Support"],
  healthcare: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Expiry Alerts", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant"],
  education: ["Sales Recording", "Staff Management", "Cash Flow Analysis", "Expense Management", "Customer Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant"],
  other: ["Sales Recording", "Inventory Tracking", "Staff Management", "Cash Flow Analysis", "Expense Management", "Customer Management", "Supplier Management", "Profit/Loss Reports", "Business Analytics", "Ask MO AI Assistant"],
};

export const PRO_ONLY_FEATURES = [
  "Multi-branch Support",
  "Production Tracking",
  "Payroll Management",
  "E-commerce Storefront",
];

export const STANDARD_OR_PRO_FEATURES = [
  "Credit Tracking",
  "Menu Management",
  "Ingredient Tracking",
];

export const COUNTRIES = [
  "Nigeria", "Ghana", "Kenya", "South Africa", "Tanzania", "Uganda", "Rwanda", "Senegal",
  "Côte d'Ivoire", "Cameroon", "Ethiopia", "Angola", "Benin", "Botswana", "Burkina Faso",
  "Burundi", "Cape Verde", "Central African Republic", "Chad", "Comoros", "Republic of the Congo",
  "Democratic Republic of the Congo", "Djibouti", "Egypt", "Equatorial Guinea", "Eritrea",
  "Eswatini", "Gabon", "Gambia", "Guinea", "Guinea-Bissau", "Lesotho", "Liberia", "Libya",
  "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia",
  "Niger", "São Tomé and Príncipe", "Somalia", "South Sudan", "Sudan", "Seychelles", "Sierra Leone",
  "Togo", "Tunisia", "Zambia", "Zimbabwe", "Other"
];

export const AFRICAN_COUNTRY_CODES = [
  { country: "Nigeria", code: "+234", flag: "🇳🇬" },
  { country: "Ghana", code: "+233", flag: "🇬🇭" },
  { country: "Kenya", code: "+254", flag: "🇰🇪" },
  { country: "South Africa", code: "+27", flag: "🇿🇦" },
  { country: "Tanzania", code: "+255", flag: "🇹🇿" },
  { country: "Uganda", code: "+256", flag: "🇺🇬" },
  { country: "Rwanda", code: "+250", flag: "🇷🇼" },
  { country: "Senegal", code: "+221", flag: "🇸🇳" },
  { country: "Côte d'Ivoire", code: "+225", flag: "🇨🇮" },
  { country: "Cameroon", code: "+237", flag: "🇨🇲" },
  { country: "Ethiopia", code: "+251", flag: "🇪🇹" },
  { country: "Angola", code: "+244", flag: "🇦🇴" },
  { country: "Benin", code: "+229", flag: "🇧🇯" },
  { country: "Botswana", code: "+267", flag: "🇧🇼" },
  { country: "Burkina Faso", code: "+226", flag: "🇧🇫" },
  { country: "Burundi", code: "+257", flag: "🇧🇮" },
  { country: "Cape Verde", code: "+238", flag: "🇨🇻" },
  { country: "Central African Republic", code: "+236", flag: "🇨🇫" },
  { country: "Chad", code: "+235", flag: "🇹🇩" },
  { country: "Comoros", code: "+269", flag: "🇰🇲" },
  { country: "Republic of the Congo", code: "+242", flag: "🇨🇬" },
  { country: "Democratic Republic of the Congo", code: "+243", flag: "🇨🇩" },
  { country: "Djibouti", code: "+253", flag: "🇩🇯" },
  { country: "Egypt", code: "+20", flag: "🇪🇬" },
  { country: "Equatorial Guinea", code: "+240", flag: "🇬🇶" },
  { country: "Eritrea", code: "+291", flag: "🇪🇷" },
  { country: "Eswatini", code: "+268", flag: "🇸🇿" },
  { country: "Gabon", code: "+241", flag: "🇬🇦" },
  { country: "Gambia", code: "+220", flag: "🇬🇲" },
  { country: "Guinea", code: "+224", flag: "🇬🇳" },
  { country: "Guinea-Bissau", code: "+245", flag: "🇬🇼" },
  { country: "Lesotho", code: "+266", flag: "🇱🇸" },
  { country: "Liberia", code: "+231", flag: "🇱🇷" },
  { country: "Libya", code: "+218", flag: "🇱🇾" },
  { country: "Madagascar", code: "+261", flag: "🇲🇬" },
  { country: "Malawi", code: "+265", flag: "🇲🇼" },
  { country: "Mali", code: "+223", flag: "🇲🇱" },
  { country: "Mauritania", code: "+222", flag: "🇲🇷" },
  { country: "Mauritius", code: "+230", flag: "🇲🇺" },
  { country: "Morocco", code: "+212", flag: "🇲🇦" },
  { country: "Mozambique", code: "+258", flag: "🇲🇿" },
  { country: "Namibia", code: "+264", flag: "🇳🇦" },
  { country: "Niger", code: "+227", flag: "🇳🇪" },
  { country: "São Tomé and Príncipe", code: "+239", flag: "🇸🇹" },
  { country: "Somalia", code: "+252", flag: "🇸🇴" },
  { country: "South Sudan", code: "+211", flag: "🇸🇸" },
  { country: "Sudan", code: "+249", flag: "🇸🇩" },
  { country: "Seychelles", code: "+248", flag: "🇸🇨" },
  { country: "Sierra Leone", code: "+232", flag: "🇸🇱" },
  { country: "Togo", code: "+228", flag: "🇹🇬" },
  { country: "Tunisia", code: "+216", flag: "🇹🇳" },
  { country: "Zambia", code: "+260", flag: "🇿🇲" },
  { country: "Zimbabwe", code: "+263", flag: "🇿🇼" },
];

export const TEAM_SIZES = [
  { id: "solo", label: "Solo", desc: "Just me", icon: "👤" },
  { id: "small", label: "2–10", desc: "Small team", icon: "👥" },
  { id: "medium", label: "11–50", desc: "Growing fast", icon: "🏢" },
  { id: "large", label: "50+", desc: "Established", icon: "🏛️" },
];

export const PLANS = [
  {
    id: "starter",
    name: "Starter",
    price: "$15",
    priceNum: 15,
    cycle: "/mo",
    tag: null,
    features: [
      "Record Sales, Expenses & Inventory",
      "Basic AI Insights (MO)",
      "Basic Online Storefront",
      "BusmoPay Payment Integration",
      "Manage up to 3 Staff",
      "Basic Sales Analytics",
    ],
    activeBg: "#F4F4F8",
    activeBorder: "#C4C4D4",
    priceColor: "#0A0A0F",
    tagBg: "",
  },
  {
    id: "standard",
    name: "Standard",
    price: "$40",
    priceNum: 40,
    cycle: "/mo",
    tag: "Most Popular",
    features: [
      "Everything in Starter",
      "Advanced AI Insights & Forecasts",
      "Professional Storefront Themes",
      "Priority Store Placement",
      "Manage up to 10 Staff",
      "Advanced Sales Analytics",
      "Advanced Forecasting",
      "Up to 3 Branches",
      "Custom Domain",
      "SEO Optimization Tools",
    ],
    activeBg: "#F3EFFE",
    activeBorder: "#6B3FE7",
    priceColor: "#6B3FE7",
    tagBg: "#6B3FE7",
  },
  {
    id: "pro",
    name: "Pro",
    price: "$80",
    priceNum: 80,
    cycle: "/mo",
    tag: "Best Value",
    features: [
      "Everything in Standard",
      "Premium AI Insights & Consulting",
      "Custom Storefront Design",
      "Featured Store Placement",
      "Unlimited Staff",
      "Custom Reports & Analytics",
      "Advanced Forecasting",
      "Unlimited Branches",
      "Production Tracking",
      "Access to Equity Investment",
      "CAC Compliance (if needed)",
      "Integrated POS & Printer",
    ],
    activeBg: "#FEF3C7",
    activeBorder: "#D97706",
    priceColor: "#D97706",
    tagBg: "#D97706",
  },
];
