// ═══════════════════════════════════════════
//  BUSMO — Shared TypeScript Types
// ═══════════════════════════════════════════

import { Key } from 'react';

export type Theme = 'light' | 'dark';

export type PageId =
  | 'home'
  | 'sale'
  | 'sales'
  | 'inventory'
  | 'expenses'
  | 'cashflow'
  | 'market'
  | 'pay'
  | 'go'
  | 'capital'
  | 'referrals'
  | 'mo'
  | 'mo-mobile'
  | 'services'
  | 'staff'
  | 'add-product'
  | 'add-expense'
  | 'statement'
  | 'reports'
  | 'bank-reconciliation'
  | 'settings'
  | 'recordsale'
  | 'money-control'
  | 'branches'
  | 'email-campaigns'
  | 'credit-tracking'
  | 'document-templates'
  | 'supplier-management'
  | 'customer-management'
  | 'payroll'
  | 'wallet'
  | 'menu-management'
  | 'margin-calculator'
  | 'can-i-buy'
  | 'ingredient-tracking'
  | 'expiry-alerts'
  | 'production-tracking'
  | 'warehouse'
  | 'stock-transfers'
  | 'audit-trail'
  | 'staff-activity'
  | 'staff-accountability'
  | 'bank-statement-import'
  | 'mo-sell'
  | 'mo-sales'
  | 'jobs'
  | 'recycling'
  | 'feature-prototype'
  | 'business-builder';
