// MO Principles Enforcer - Enforce Response Principles
// Ensures all responses follow MO's core principles

export interface PrincipleViolation {
  principle: string;
  description: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  location: string;
  suggestion: string;
}

export interface PrinciplesCheckResult {
  valid: boolean;
  violations: PrincipleViolation[];
  score: number; // 0-100
}

export interface ResponseContent {
  message: string;
  sections?: any[];
  context?: any;
}

export class PrinciplesEnforcer {
  
  // Core principles to enforce
  private principles = [
    {
      name: 'No Repetition',
      description: 'Never repeat information unnecessarily',
      check: this.checkNoRepetition.bind(this),
    },
    {
      name: 'No Generic Statements',
      description: 'Never give generic motivational statements',
      check: this.checkNoGenericStatements.bind(this),
    },
    {
      name: 'No Obvious Explanations',
      description: 'Never explain obvious things',
      check: this.checkNoObviousExplanations.bind(this),
    },
    {
      name: 'Use Business Context',
      description: 'Never ignore business context',
      check: this.checkUseBusinessContext.bind(this),
    },
    {
      name: 'Use Previous Conversations',
      description: 'Never ignore previous conversations',
      check: this.checkUsePreviousConversations.bind(this),
    },
    {
      name: 'Think Ahead',
      description: 'Never stop at answering the question',
      check: this.checkThinkAhead.bind(this),
    },
    {
      name: 'Prioritize Actions',
      description: 'Always prioritize actions that move the business forward',
      check: this.checkPrioritizeActions.bind(this),
    },
    {
      name: 'Explain Assumptions',
      description: 'Always explain assumptions behind estimates',
      check: this.checkExplainAssumptions.bind(this),
    },
    {
      name: 'Distinguish Facts from Estimates',
      description: 'Always distinguish between facts provided by user and estimates generated by MO',
      check: this.checkDistinguishFactsFromEstimates.bind(this),
    },
    {
      name: 'Be Concise',
      description: 'Keep responses concise but never sacrifice useful reasoning',
      check: this.checkBeConcise.bind(this),
    },
  ];
  
  // Generic phrases to avoid
  private genericPhrases = [
    'great initiative',
    'fantastic business',
    'excellent idea',
    'happy to help',
    'good luck',
    'that\'s wonderful',
    'amazing',
    'awesome',
    'brilliant',
    'perfect',
    'love it',
    'congratulations',
    'well done',
    'great job',
    'keep it up',
    'you\'re doing great',
    'that\'s great',
    'sounds good',
    'sounds great',
    'nice work',
    'good for you',
    'that\'s a good idea',
    'i think that\'s a good idea',
    'i agree',
    'totally agree',
    'completely agree',
    'absolutely',
    'definitely',
    'certainly',
    'of course',
    'sure thing',
    'no problem',
    'not a problem',
    'you\'re welcome',
    'my pleasure',
  ];
  
  // Obvious explanations to avoid
  private obviousPatterns = [
    /as you know/i,
    /obviously/i,
    /it goes without saying/i,
    /clearly/i,
    /naturally/i,
    /of course/i,
    /it\'s (obvious|clear) that/i,
  ];
  
  // Check response against all principles
  checkPrinciples(content: ResponseContent): PrinciplesCheckResult {
    const violations: PrincipleViolation[] = [];
    
    this.principles.forEach(principle => {
      const violation = principle.check(content);
      if (violation) {
        violations.push(violation);
      }
    });
    
    // Calculate score
    const score = Math.max(0, 100 - (violations.length * 10) - violations.reduce((sum, v) => {
      const severityScore = { critical: 25, high: 15, medium: 10, low: 5 };
      return sum + severityScore[v.severity];
    }, 0));
    
    return {
      valid: violations.length === 0,
      violations,
      score,
    };
  }
  
  // Check: No Repetition
  private checkNoRepetition(content: ResponseContent): PrincipleViolation | null {
    const message = content.message.toLowerCase();
    const sentences = message.split(/[.!?]+/).filter(s => s.trim().length > 0);
    
    // Check for duplicate sentences
    const sentenceSet = new Set(sentences.map(s => s.trim()));
    if (sentenceSet.size < sentences.length) {
      return {
        principle: 'No Repetition',
        description: 'Response contains duplicate sentences or content',
        severity: 'medium',
        location: 'Response content',
        suggestion: 'Remove duplicate content and consolidate similar points',
      };
    }
    
    // Check for repeated phrases
    const words = message.split(/\s+/);
    const phraseRepeats: Record<string, number> = {};
    
    for (let i = 0; i < words.length - 2; i++) {
      const phrase = `${words[i]} ${words[i + 1]} ${words[i + 2]}`;
      phraseRepeats[phrase] = (phraseRepeats[phrase] || 0) + 1;
    }
    
    const repeatedPhrases = Object.entries(phraseRepeats).filter(([_, count]) => count > 2);
    if (repeatedPhrases.length > 0) {
      return {
        principle: 'No Repetition',
        description: 'Response contains repeated phrases',
        severity: 'low',
        location: 'Response content',
        suggestion: 'Vary language and avoid repeating the same phrases',
      };
    }
    
    return null;
  }
  
  // Check: No Generic Statements
  private checkNoGenericStatements(content: ResponseContent): PrincipleViolation | null {
    const message = content.message.toLowerCase();
    
    for (const phrase of this.genericPhrases) {
      if (message.includes(phrase)) {
        return {
          principle: 'No Generic Statements',
          description: `Response contains generic phrase: "${phrase}"`,
          severity: 'medium',
          location: 'Response content',
          suggestion: 'Remove generic motivational phrases and focus on actionable content',
        };
      }
    }
    
    return null;
  }
  
  // Check: No Obvious Explanations
  private checkNoObviousExplanations(content: ResponseContent): PrincipleViolation | null {
    const message = content.message.toLowerCase();
    
    for (const pattern of this.obviousPatterns) {
      if (pattern.test(message)) {
        return {
          principle: 'No Obvious Explanations',
          description: 'Response explains obvious things',
          severity: 'low',
          location: 'Response content',
          suggestion: 'Remove explanations of obvious concepts and focus on insights',
        };
      }
    }
    
    return null;
  }
  
  // Check: Use Business Context
  private checkUseBusinessContext(content: ResponseContent): PrincipleViolation | null {
    if (!content.context) {
      return {
        principle: 'Use Business Context',
        description: 'No business context provided for validation',
        severity: 'low',
        location: 'Context',
        suggestion: 'Provide business context for better validation',
      };
    }
    
    const message = content.message.toLowerCase();
    const context = content.context;
    
    // Check if response references business context
    const hasContextReference = 
      (context.industry && message.includes(context.industry.toLowerCase())) ||
      (context.stage && message.includes(context.stage.toLowerCase())) ||
      (context.location && message.includes(context.location.toLowerCase())) ||
      (context.capital && message.includes('capital')) ||
      (context.cash && message.includes('cash'));
    
    if (!hasContextReference && (context.industry || context.stage || context.capital)) {
      return {
        principle: 'Use Business Context',
        description: 'Response does not reference available business context',
        severity: 'high',
        location: 'Response content',
        suggestion: 'Incorporate relevant business context (industry, stage, capital, etc.) into response',
      };
    }
    
    return null;
  }
  
  // Check: Use Previous Conversations
  private checkUsePreviousConversations(content: ResponseContent): PrincipleViolation | null {
    if (!content.context?.conversationHistory || content.context.conversationHistory.length === 0) {
      return null; // No previous conversations to reference
    }
    
    const message = content.message.toLowerCase();
    const conversationHistory = content.context.conversationHistory;
    
    // Check if response acknowledges previous context
    const hasPreviousReference = message.includes('previously') || 
                                  message.includes('earlier') ||
                                  message.includes('as we discussed') ||
                                  message.includes('from our conversation');
    
    // This is a soft check - not all responses need to reference previous conversations
    // Only flag if it seems like the response should reference previous context but doesn't
    return null;
  }
  
  // Check: Think Ahead
  private checkThinkAhead(content: ResponseContent): PrincipleViolation | null {
    const message = content.message.toLowerCase();
    
    // Check if response includes forward-looking content
    const hasForwardLooking = 
      message.includes('next') ||
      message.includes('future') ||
      message.includes('plan') ||
      message.includes('should consider') ||
      message.includes('recommend') ||
      message.includes('will need') ||
      message.includes('upcoming') ||
      message.includes('anticipate');
    
    if (!hasForwardLooking) {
      return {
        principle: 'Think Ahead',
        description: 'Response does not look ahead or anticipate next needs',
        severity: 'high',
        location: 'Response content',
        suggestion: 'Add forward-looking content: next steps, future considerations, or anticipated needs',
      };
    }
    
    return null;
  }
  
  // Check: Prioritize Actions
  private checkPrioritizeActions(content: ResponseContent): PrincipleViolation | null {
    const message = content.message.toLowerCase();
    
    // Check if response includes actionable content
    const hasActionable = 
      message.includes('should') ||
      message.includes('recommend') ||
      message.includes('action') ||
      message.includes('do') ||
      message.includes('implement') ||
      message.includes('execute') ||
      message.includes('take') ||
      message.includes('step');
    
    if (!hasActionable) {
      return {
        principle: 'Prioritize Actions',
        description: 'Response lacks actionable recommendations',
        severity: 'critical',
        location: 'Response content',
        suggestion: 'Include specific, actionable recommendations that move the business forward',
      };
    }
    
    return null;
  }
  
  // Check: Explain Assumptions
  private checkExplainAssumptions(content: ResponseContent): PrincipleViolation | null {
    const message = content.message.toLowerCase();
    
    // Check if response includes estimates or projections
    const hasEstimates = 
      message.includes('estimate') ||
      message.includes('project') ||
      message.includes('forecast') ||
      message.includes('approximately') ||
      message.includes('around') ||
      message.includes('roughly');
    
    if (hasEstimates) {
      // Check if assumptions are explained
      const hasAssumptionsExplained = 
        message.includes('assuming') ||
        message.includes('based on') ||
        message.includes('this assumes') ||
        message.includes('assuming that');
      
      if (!hasAssumptionsExplained) {
        return {
          principle: 'Explain Assumptions',
          description: 'Response includes estimates without explaining assumptions',
          severity: 'medium',
          location: 'Response content',
          suggestion: 'Explain the assumptions behind estimates and projections',
        };
      }
    }
    
    return null;
  }
  
  // Check: Distinguish Facts from Estimates
  private checkDistinguishFactsFromEstimates(content: ResponseContent): PrincipleViolation | null {
    const message = content.message.toLowerCase();
    
    // This is a nuanced check - look for clear distinction markers
    const hasFactMarkers = 
      message.includes('you mentioned') ||
      message.includes('you stated') ||
      message.includes('according to your data') ||
      message.includes('based on what you said');
    
    const hasEstimateMarkers = 
      message.includes('i estimate') ||
      message.includes('my calculation') ||
      message.includes('based on available data') ||
      message.includes('this is an estimate');
    
    // If response has both facts and estimates, check if they're distinguished
    if (hasFactMarkers && hasEstimateMarkers) {
      return null; // Good - both are distinguished
    }
    
    // This is a soft check - not all responses will have both
    return null;
  }
  
  // Check: Be Concise
  private checkBeConcise(content: ResponseContent): PrincipleViolation | null {
    const message = content.message;
    const wordCount = message.split(/\s+/).length;
    
    // Very long responses might be unnecessarily verbose
    if (wordCount > 500) {
      return {
        principle: 'Be Concise',
        description: `Response is very long (${wordCount} words)`,
        severity: 'low',
        location: 'Response content',
        suggestion: 'Consider condensing the response while retaining key information',
      };
    }
    
    return null;
  }
  
  // Auto-fix violations
  autoFix(content: ResponseContent): ResponseContent {
    let message = content.message;
    
    // Remove generic phrases
    this.genericPhrases.forEach(phrase => {
      const regex = new RegExp(phrase, 'gi');
      message = message.replace(regex, '');
    });
    
    // Clean up multiple spaces
    message = message.replace(/\s+/g, ' ').trim();
    
    // Remove obvious explanation patterns
    this.obviousPatterns.forEach(pattern => {
      message = message.replace(pattern, '');
    });
    
    // Clean up again after removals
    message = message.replace(/\s+/g, ' ').trim();
    
    return {
      ...content,
      message,
    };
  }
  
  // Get principles summary
  getPrinciplesSummary(): string {
    return `
MO Core Principles:
1. Never repeat information unnecessarily
2. Never give generic motivational statements
3. Never explain obvious things
4. Never ignore business context
5. Never ignore previous conversations
6. Never stop at answering the question
7. Always prioritize actions that move the business forward
8. Always explain assumptions behind estimates
9. Always distinguish between facts provided by user and estimates generated by MO
10. Keep responses concise but never sacrifice useful reasoning
    `.trim();
  }
}

// Singleton instance
let principlesEnforcerInstance: PrinciplesEnforcer | null = null;

export function getPrinciplesEnforcer(): PrinciplesEnforcer {
  if (!principlesEnforcerInstance) {
    principlesEnforcerInstance = new PrinciplesEnforcer();
  }
  return principlesEnforcerInstance;
}
